config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new', as: 'Livros'
  get 'admin/index'

  get 'sessions/new'

  get 'sessions/create'
  post 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :books

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  post 'books/ordenar', as: 'ordenar'

end

app/models/book.rb
class Book < ActiveRecord::Base
	validates :titulo, :autores, :editora, :anoPublica, :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains
	private
		def ensure_an_admin_remains
			if User.count.zero?
				raise "Can't delete last user"
			end
		end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	@total_books = Book.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  before_action :authorize
	protected
	def authorize
		unless User.find_by(id: session[:user_id])
			redirect_to login_url, notice: "Please log in"
		end
	end
	
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  #skip_before_action :authorize
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction 

  # GET /books
  # GET /books.json
  def index
    @books = Book.where (["user_id = ? and perdido = ?", session[:user_id], false])
    #User.where(["name = ? and email = ?", "Joe", "joe@example.com"])
  end
  def ordenar
    @books = Book.order(:titulo).where "user_id = ?", session[:user_id]
    respond_to do |format|
      format.js
    end
  end 

  # GET /books/1
  # GET /books/1.json
  def show
    if @book.perdido
      @perdidoFrase = "Livro perdido"
    else
      @perdidoFrase = "Livro no avervo"
    end
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        #format.js { }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:titulo, :autores, :editora, :anoPublica, :user_id, :perdido)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :authorize
  def new # index

  end

  def create # login
  	user = User.find_by(name: params[:name])
		if user and user.authenticate(params[:password])
			session[:user_id] = user.id

			session[:user_name] = user.name
			redirect_to books_path
		else
			redirect_to login_url, alert: "Invalid user/password combination"
		end
  end

  def destroy # logout
  	session[:user_id] = nil
		redirect_to login_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, only: :new
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
    #@users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully created." }
        #format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully updated." }
        #format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    begin
    @user.destroy
    flash[:notice] = "User #{@user.name} deleted"
    rescue StandardError => e
      flash[:notice] = e.message
    end


    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)  
    title ||= column.titleize  
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil  
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"  
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}  
  end 
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_books, "order") %>.

app/views/books/_book.html.erb
      <tr>
        <td><%= book.titulo %></td>
        <td><%= book.autores %></td>
        <td><%= book.editora %></td>
        <td><%= book.anoPublica %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

app/views/books/_books.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate @products %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :autores %><br>
    <%= f.text_field :autores %>
  </div>
  <div class="field">
    <%= f.label :editora %><br>
    <%= f.text_field :editora %>
  </div>
  <div class="field">
    <input type="hidden" name="book[user_id]" value="<%= session[:user_id] %>" id="book_user_id">
    <%= f.label :anoPublica %><br>
    <%= f.number_field :anoPublica %>
  </div>
  <div class="field">
    <%= f.label :perdido %><br>
    <label> Não </label>
    <%= f.radio_button :perdido, "0" %>
    <label>Sim </label>
    <%= f.radio_button :perdido, "1" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/books_custom.js.erb
<script type="text/javascript">
$(document).ready(function() {
    $("#current_books").click(function(){
      $("th").html("<%= @test %>");
    });
});

</script>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<%= button_to "ordenar", ordenar_path , remote: true %>
<table id="ordernarTitulo">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Autores</th>
      <th>Editora</th>
      <th>Anopublica</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render(@books) %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/ordenar.js.erb
$('tbody').html("<%= escape_javascript render(@books)%>");

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @book.titulo %>
</p>

<p>
  <strong>Autores:</strong>
  <%= @book.autores %>
</p>

<p>
  <strong>Editora:</strong>
  <%= @book.editora %>
</p>

<p>
  <strong>Anopublica:</strong>
  <%= @book.anoPublica %>
</p>
<p>
  <strong>Perdido :</strong>
  <%= @perdidoFrase %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BibliotecaPessoal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p> <%= session[:user_name] %> </p>
<%= link_to 'New User', new_user_path %>
	<% if session[:user_id] %>
		<ul>
			<li><%= link_to 'User',users_path%></li>
      <li><%= link_to 'Books',books_path%></li>
		</ul>
		<%= button_to 'Logout', logout_path, method: :delete %>
	<% end %>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>